services:
  agent:
    build: .
    container_name: agent
    image: t-agent:latest
    restart: unless-stopped
    # google auth uses random ports for callbacks, so we need to expose them
    ports:
      - "34117:34117"
      - "44081:44081"
    volumes:
      - /home/$USER/workspace:/home/agent/workspace
      - home:/home/agent
    stdin_open: true
    tty: true
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          memory: 6G
          cpus: '2.0'
    network_mode: "bridge"

volumes:
  home:
    driver: local
