services:
  agent:
    build: .
    container_name: agent
    image: t-agent:latest
    restart: unless-stopped
    volumes:
      - /home/$USER/workspace:/home/agent/workspace
      - home:/home/agent
    stdin_open: true
    tty: true
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          memory: 6G
          cpus: '2.0'
    network_mode: "bridge"

volumes:
  home:
    driver: local
